//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddtionAnalysis {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PartOfSpeech {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PartOfSpeech() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddtionAnalysis.PartOfSpeech", typeof(PartOfSpeech).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 形容词 的本地化字符串。
        /// </summary>
        internal static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 副形词 的本地化字符串。
        /// </summary>
        internal static string ad {
            get {
                return ResourceManager.GetString("ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附加关系 的本地化字符串。
        /// </summary>
        internal static string ADJ {
            get {
                return ResourceManager.GetString("ADJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状中结构 的本地化字符串。
        /// </summary>
        internal static string ADV {
            get {
                return ResourceManager.GetString("ADV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 形语素 的本地化字符串。
        /// </summary>
        internal static string Ag {
            get {
                return ResourceManager.GetString("Ag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名形词 的本地化字符串。
        /// </summary>
        internal static string an {
            get {
                return ResourceManager.GetString("an", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 lXSvzb3iZlvvoqlgB25YlWGS 的本地化字符串。
        /// </summary>
        internal static string API_KEY {
            get {
                return ResourceManager.GetString("API_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同位关系 的本地化字符串。
        /// </summary>
        internal static string APP {
            get {
                return ResourceManager.GetString("APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 15419388 的本地化字符串。
        /// </summary>
        internal static string APP_ID {
            get {
                return ResourceManager.GetString("APP_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定中关系 的本地化字符串。
        /// </summary>
        internal static string ATT {
            get {
                return ResourceManager.GetString("ATT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区别词 的本地化字符串。
        /// </summary>
        internal static string b {
            get {
                return ResourceManager.GetString("b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “把”字结构 的本地化字符串。
        /// </summary>
        internal static string BA {
            get {
                return ResourceManager.GetString("BA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “被”字结构 的本地化字符串。
        /// </summary>
        internal static string BEI {
            get {
                return ResourceManager.GetString("BEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连词 的本地化字符串。
        /// </summary>
        internal static string c {
            get {
                return ResourceManager.GetString("c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动补结构 的本地化字符串。
        /// </summary>
        internal static string CMP {
            get {
                return ResourceManager.GetString("CMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关联词 的本地化字符串。
        /// </summary>
        internal static string CNJ {
            get {
                return ResourceManager.GetString("CNJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合同相关 的本地化字符串。
        /// </summary>
        internal static string CON {
            get {
                return ResourceManager.GetString("CON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 并列关系 的本地化字符串。
        /// </summary>
        internal static string COO {
            get {
                return ResourceManager.GetString("COO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 费用 的本地化字符串。
        /// </summary>
        internal static string COST {
            get {
                return ResourceManager.GetString("COST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关联结构 的本地化字符串。
        /// </summary>
        internal static string CS {
            get {
                return ResourceManager.GetString("CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 副词 的本地化字符串。
        /// </summary>
        internal static string d {
            get {
                return ResourceManager.GetString("d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 兼语结构 的本地化字符串。
        /// </summary>
        internal static string DBL {
            get {
                return ResourceManager.GetString("DBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 依存分句 的本地化字符串。
        /// </summary>
        internal static string DC {
            get {
                return ResourceManager.GetString("DC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “的”字结构 的本地化字符串。
        /// </summary>
        internal static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “得”字结构 的本地化字符串。
        /// </summary>
        internal static string DEI {
            get {
                return ResourceManager.GetString("DEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 副语素 的本地化字符串。
        /// </summary>
        internal static string dg {
            get {
                return ResourceManager.GetString("dg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “地”字结构 的本地化字符串。
        /// </summary>
        internal static string DI {
            get {
                return ResourceManager.GetString("DI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双宾语 的本地化字符串。
        /// </summary>
        internal static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 叹词 的本地化字符串。
        /// </summary>
        internal static string e {
            get {
                return ResourceManager.GetString("e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方位名词 的本地化字符串。
        /// </summary>
        internal static string f {
            get {
                return ResourceManager.GetString("f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前置宾语 的本地化字符串。
        /// </summary>
        internal static string FOB {
            get {
                return ResourceManager.GetString("FOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语素 的本地化字符串。
        /// </summary>
        internal static string g {
            get {
                return ResourceManager.GetString("g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前接成分 的本地化字符串。
        /// </summary>
        internal static string h {
            get {
                return ResourceManager.GetString("h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 核心 的本地化字符串。
        /// </summary>
        internal static string HED {
            get {
                return ResourceManager.GetString("HED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成语 的本地化字符串。
        /// </summary>
        internal static string i {
            get {
                return ResourceManager.GetString("i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 独立分句 的本地化字符串。
        /// </summary>
        internal static string IC {
            get {
                return ResourceManager.GetString("IC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 独立结构 的本地化字符串。
        /// </summary>
        internal static string IS {
            get {
                return ResourceManager.GetString("IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简称略语 的本地化字符串。
        /// </summary>
        internal static string j {
            get {
                return ResourceManager.GetString("j", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后接成分 的本地化字符串。
        /// </summary>
        internal static string k {
            get {
                return ResourceManager.GetString("k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2 的本地化字符串。
        /// </summary>
        internal static string KTV {
            get {
                return ResourceManager.GetString("KTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 习用语 的本地化字符串。
        /// </summary>
        internal static string l {
            get {
                return ResourceManager.GetString("l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地名|处所关系 的本地化字符串。
        /// </summary>
        internal static string LOC {
            get {
                return ResourceManager.GetString("LOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量词 的本地化字符串。
        /// </summary>
        internal static string m {
            get {
                return ResourceManager.GetString("m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语态结构 的本地化字符串。
        /// </summary>
        internal static string MT {
            get {
                return ResourceManager.GetString("MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普通名词 的本地化字符串。
        /// </summary>
        internal static string n {
            get {
                return ResourceManager.GetString("n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名语素 的本地化字符串。
        /// </summary>
        internal static string Ng {
            get {
                return ResourceManager.GetString("Ng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人名 的本地化字符串。
        /// </summary>
        internal static string nr {
            get {
                return ResourceManager.GetString("nr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地名 的本地化字符串。
        /// </summary>
        internal static string ns {
            get {
                return ResourceManager.GetString("ns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机构团体名 的本地化字符串。
        /// </summary>
        internal static string nt {
            get {
                return ResourceManager.GetString("nt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作品名 的本地化字符串。
        /// </summary>
        internal static string nw {
            get {
                return ResourceManager.GetString("nw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他专名 的本地化字符串。
        /// </summary>
        internal static string nz {
            get {
                return ResourceManager.GetString("nz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拟声词 的本地化字符串。
        /// </summary>
        internal static string o {
            get {
                return ResourceManager.GetString("o", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机构名 的本地化字符串。
        /// </summary>
        internal static string ORG {
            get {
                return ResourceManager.GetString("ORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 介词 的本地化字符串。
        /// </summary>
        internal static string p {
            get {
                return ResourceManager.GetString("p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人名 的本地化字符串。
        /// </summary>
        internal static string PER {
            get {
                return ResourceManager.GetString("PER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 介宾关系 的本地化字符串。
        /// </summary>
        internal static string POB {
            get {
                return ResourceManager.GetString("POB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 量词 的本地化字符串。
        /// </summary>
        internal static string q {
            get {
                return ResourceManager.GetString("q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量关系 的本地化字符串。
        /// </summary>
        internal static string QUN {
            get {
                return ResourceManager.GetString("QUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代词 的本地化字符串。
        /// </summary>
        internal static string r {
            get {
                return ResourceManager.GetString("r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处所名词 的本地化字符串。
        /// </summary>
        internal static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主谓关系 的本地化字符串。
        /// </summary>
        internal static string SBV {
            get {
                return ResourceManager.GetString("SBV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IoU4AvyqsmZbUA9G49ewPPQmWTIhrTEk 的本地化字符串。
        /// </summary>
        internal static string SECRET_KEY {
            get {
                return ResourceManager.GetString("SECRET_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 比拟关系 的本地化字符串。
        /// </summary>
        internal static string SIM {
            get {
                return ResourceManager.GetString("SIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “所”字结构 的本地化字符串。
        /// </summary>
        internal static string SUO {
            get {
                return ResourceManager.GetString("SUO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间名词 的本地化字符串。
        /// </summary>
        internal static string t {
            get {
                return ResourceManager.GetString("t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时语素 的本地化字符串。
        /// </summary>
        internal static string tg {
            get {
                return ResourceManager.GetString("tg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        internal static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间关系 的本地化字符串。
        /// </summary>
        internal static string TMP {
            get {
                return ResourceManager.GetString("TMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        internal static string TOP {
            get {
                return ResourceManager.GetString("TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 助词 的本地化字符串。
        /// </summary>
        internal static string u {
            get {
                return ResourceManager.GetString("u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知词 的本地化字符串。
        /// </summary>
        internal static string un {
            get {
                return ResourceManager.GetString("un", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普通动词 的本地化字符串。
        /// </summary>
        internal static string v {
            get {
                return ResourceManager.GetString("v", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动副词 的本地化字符串。
        /// </summary>
        internal static string vd {
            get {
                return ResourceManager.GetString("vd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动语素 的本地化字符串。
        /// </summary>
        internal static string vg {
            get {
                return ResourceManager.GetString("vg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名动词 的本地化字符串。
        /// </summary>
        internal static string vn {
            get {
                return ResourceManager.GetString("vn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 叠词关系 的本地化字符串。
        /// </summary>
        internal static string VNV {
            get {
                return ResourceManager.GetString("VNV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动宾关系 的本地化字符串。
        /// </summary>
        internal static string VOB {
            get {
                return ResourceManager.GetString("VOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连谓结构 的本地化字符串。
        /// </summary>
        internal static string VV {
            get {
                return ResourceManager.GetString("VV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标点符号 的本地化字符串。
        /// </summary>
        internal static string w {
            get {
                return ResourceManager.GetString("w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标点 的本地化字符串。
        /// </summary>
        internal static string WP {
            get {
                return ResourceManager.GetString("WP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非语素字 的本地化字符串。
        /// </summary>
        internal static string x {
            get {
                return ResourceManager.GetString("x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他虚词 的本地化字符串。
        /// </summary>
        internal static string xc {
            get {
                return ResourceManager.GetString("xc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语气词 的本地化字符串。
        /// </summary>
        internal static string y {
            get {
                return ResourceManager.GetString("y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一个词 的本地化字符串。
        /// </summary>
        internal static string YGC {
            get {
                return ResourceManager.GetString("YGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态词 的本地化字符串。
        /// </summary>
        internal static string z {
            get {
                return ResourceManager.GetString("z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 的本地化字符串。
        /// </summary>
        internal static string 丽人 {
            get {
                return ResourceManager.GetString("丽人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6 的本地化字符串。
        /// </summary>
        internal static string 健康 {
            get {
                return ResourceManager.GetString("健康", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8 的本地化字符串。
        /// </summary>
        internal static string 商业 {
            get {
                return ResourceManager.GetString("商业", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 9 的本地化字符串。
        /// </summary>
        internal static string 房产 {
            get {
                return ResourceManager.GetString("房产", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7 的本地化字符串。
        /// </summary>
        internal static string 教育 {
            get {
                return ResourceManager.GetString("教育", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 13 的本地化字符串。
        /// </summary>
        internal static string 数码 {
            get {
                return ResourceManager.GetString("数码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5 的本地化字符串。
        /// </summary>
        internal static string 旅游 {
            get {
                return ResourceManager.GetString("旅游", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10 的本地化字符串。
        /// </summary>
        internal static string 汽车 {
            get {
                return ResourceManager.GetString("汽车", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 11 的本地化字符串。
        /// </summary>
        internal static string 生活 {
            get {
                return ResourceManager.GetString("生活", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4 的本地化字符串。
        /// </summary>
        internal static string 美食餐饮 {
            get {
                return ResourceManager.GetString("美食餐饮", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12 的本地化字符串。
        /// </summary>
        internal static string 购物 {
            get {
                return ResourceManager.GetString("购物", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        internal static string 酒店 {
            get {
                return ResourceManager.GetString("酒店", resourceCulture);
            }
        }
    }
}
